media: media
content:
  - name: komarigoto
    label: 困りごと
    type: collection
    path: docs
    operations:
      rename: false
      delete: false
    fields:
      - name: title
        label: タイトル
        type: string
      - name: body
        label: 本文
        type: rich-text
        options:
          media: false
          switcher: false
